SUPABASE_URL = "https://ilxnstbccchtutsgudwx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlseG5zdGJjY2NodHV0c2d1ZHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDc1NjUsImV4cCI6MjA3NzgyMzU2NX0.4DkC7Na70P71lKfcmLlJ5juc5VpkXdi1yJWwLDkhXnA"
